### ISSUE TITLE
스터디방식 조정

### ISSUE THREAD

**Issue by Cha-Ji** [16-SulGore/Algorithm#18]
## 문제점

- B+Tree를 구현해보며 이해를 확실히 하려 했으나, 공부효율이 좋지않았음.
- 백준 문제풀이를 각자 해오니 우선순위가 밀려 진도가 제각각임.

## 해결방안

- [ ] 알고리즘 구현
     - 기초(머지, 퀵, 다익) 정도만 해보는게 좋은듯
- [ ] 모각코
    - 모각코 형식으로 2시간 풀고 PR -> 잠깐쉬고 코드리뷰
    - 백준 그룹에 대회 형식으로 문제 출제 or 기출문제 풀이
- [ ] 출제
    - (실전)3시간 정도의 분량을 출제해서 빠듯하게 vs (연습)2문제 정도 출제해서 완벽하게

**Comment by jihun-24k** [comment]
기초적인 알고리즘 포함 자료구조같은 것도 좋을꺼 같네요!
출제 방식은 전 후자(연습)로 하다가 한달에 한번씩 전차(실전)처럼 빠듯하게 푸는건 어떤지 궁금하네요

**Comment by Cha-Ji** [comment]
1. 알고리즘 구현 -> 강의형 스터디를 개설, 발표형 스터디를 개설
2. 문제풀이 -> 어렵다, 문제가 많다, 시간을 적게 투자한다.
3. 함께할 수 있는 것 -> 대회 출전, 비공식 코드포스 백준, 기출문제풀이
