### ISSUE TITLE
첫주차 문제

### ISSUE THREAD

**Issue by Cha-Ji** [16-SulGore/Algorithm#26]
## 링크
- [오픈채팅방](https://programmers.co.kr/learn/courses/30/lessons/42888?language=python3)
- ~~[카카오프렌즈 컬러링북](https://programmers.co.kr/learn/courses/30/lessons/1829)~~
- ~~[단체사진 찍기](https://programmers.co.kr/learn/courses/30/lessons/1835)~~
- [메뉴 리뉴얼](https://programmers.co.kr/learn/courses/30/lessons/72411)
- [괄호 변환](https://programmers.co.kr/learn/courses/30/lessons/60058)

## 비고
내가 안푼 문제로 구성함 ㅋㅋ

**Comment by Cha-Ji** [comment]
아니 메뉴 리뉴얼 왤캐 어려움??

**Comment by dohun31** [comment]
저 그거 풀다가 빡쳐서 뛰어넘었어요 ㅋㅋ

**Comment by Cha-Ji** [comment]
나도 포기 ㅋㅋㅋ
