### ISSUE TITLE
이후 방향

### ISSUE THREAD

**Issue by Cha-Ji** [16-SulGore/Algorithm#78]
> 9월 대국민 카카오 코테와 기타 공채를 위한 꾸준한 4개월 공부

### 일정
- 스터디는 부담감을 더는 것을 1차 목표로 한다.
- 따라서, 월요일 기준으로 출제와 merge를 하며 코드리뷰만 계속하는 기존 형태를 유지한다.
- 이제는 언어가 다르기 때문에 리뷰가 많이 달리지 않을 것을 감수한다.
- 문제는 2 ~ 7문제 정도 출제한다.

### 커리큘럼
- 초반에는 한달간 공부한 지식 굳히기
  - 투포인터, 누적합, 빡구현
- 중반에는 고난이도와 곁들여 개념학습과 익숙하지 않은 지식 학습
  - 상: dp + bfs, 카카오 4레벨 빡구현
  - 익숙하지 않은: 그래프(다익, 플로이드, 스패닝트리, 위상정렬), 
  - 개념: 트리(레드블랙, B+, 트라이, 세그트리, 펜윅트리 등), 우선순위 큐, 힙
- 후반에는 기출 문제와 심화 문제로 출제한다.
  - 기출: 문자열 다루기, 빡구현, 삼성 bfs
  - 심화: 그리디, dp 심화, 이진법

**Comment by dohun31** [comment]
뭐야 이제봤어요 이럴수가
