### ISSUE TITLE
네이버 코딩테스트 대비하기

### ISSUE THREAD

**Issue by Cha-Ji** [16-SulGore/Algorithm#80]
> 다양한 의견 남겨주세요. 6/9 목요일까지 의견받습니다.

### 일정
- 7월 2일 토요일 (공채기준) 코딩테스트를 대비합니다.
- 목요일까지 리뷰.
- 금요일 merge & 출제.
- 6/17, 6/24, 7/1 세번 merge합니다.

### 목표
- 네이버는 기본기 위주의 문제가 나오는 것으로 알고 있습니다. 추가정보 있으면 달아주세요.
- 1. 슬라이딩 윈도우, 이진탐색 2. 완탐 3. 카카오 기출 세 번 풀면 어떨까 싶습니다.
  - 앞에 2주는 백준 마지막주는 프로그래머스입니다.

**Comment by dohun31** [comment]
저 참여하겠습니다~ 

기본기 위주 너무 좋습니다. 저는 항상 빡구현이나 완전탐색같은거 나오면 삐끗하더라구요😂

> _인턴 코테는 `6.16(목) - 6.30(목)` 사이에 치뤄지는거 같아요_

**Comment by Cha-Ji** [comment]
리드미 반영완료
